baseURL = "http://www.hicape.com"
languageCode = "zh-CN"
title = "CAPE|全球青年实践网络"
publishdir = "docs"
theme="maupassant-hugo"

hasCJKLanguage = true

summaryLength = 240

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4


[[params.ads]]
  title = "CAPE"
  url = "/"
  img = "https://i.loli.net/2019/05/28/5ced34979409c95042.jpg"

[[params.links]]
  title = "ActionThinker "
  name = "ActionThinker"
  url = "https://actionthinker.com/"
[[params.links]]
  title = "手艺人赵鹏 "
  name = "手艺人赵鹏"
  url = "https://zhaopeng.me"


[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[params.utteranc]
    enable = true
    repo = "ActionThinker/cape"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[author]
  name = "CAPE"

[params]
  author = "CAPE"
  subtitle = "让青年发展成为社会议题"
  keywords = "青年发展,社会创新,返乡青年,中国走出去,环球游学,留学,海外实习,世界公民,公益,国际志愿者,大学生,青年"
  description = "CAPE是一个全球青年实践网络,由青年和学生在2011年6月份发起的,旨在借助当代青年和学生在全球化的教育、经济和文化中的实践和观察,共同探索我们新的未来。"
