baseURL = "http://www.hicape.com"
languageCode = "zh-CN"
title = "CAPE|全球青年实践网络"
theme = "maupassant"

[author]
  name = "CAPE"

[params]
  author = "CAPE"
  subtitle = "让青年发展成为社会议题"
  keywords = "青年发展,社会创新,返乡青年,中国走出去,环球游学,留学,海外实习,世界公民,公益,国际志愿者,大学生,青年"
  description = "CAPE是一个全球青年实践网络,由青年和学生在2011年6月份发起的,旨在借助当代青年和学生在全球化的教育、经济和文化中的实践和观察,共同探索我们新的未来。"
